# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    - coverage/

stages:
  - install
  - test
  - quality
  - build

install_job:
  stage: install
  script: npm install

test_job:
  stage: test
  script: npm run test

lint_job:
  stage: quality
  script: npm run lint

sonarqube-reports:
  stage: quality
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: $SONAR_URL
    SONAR_ANALYSIS_MODE: publish
    SONAR_BRANCH: $CI_COMMIT_REF_SLUG
  script:
    - gitlab-sonar-scanner -Dsonar.login=$SONAR_LOGIN

build_job:
  stage: build
  script: npm run build
